### ISSUE TITLE
Cannot run from a thread other than main

### ISSUE THREAD

**Issue by LilithHafner** [Akul-AI/rlvoice#3]
This is a MWE demonstrating the problem:
```python
import rlvoice, threading

def f(engine):
    engine.say("First sentence.")
    engine.runAndWait()
    engine.say("Second sentence.")
    engine.runAndWait()

engine = rlvoice.init()
f(engine)
threading.Thread(target=f, args=(engine,)).start()
```
Audible output "First sentence. Second sentence. First sentence."
Text output:
```
Exception in thread Thread-1 (f):
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "<stdin>", line 5, in f
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/rlvoice/engine.py", line 180, in runAndWait
    raise RuntimeError('run loop already started')
RuntimeError: run loop already started
```
instantiating `engine` and/or importing `rlvoice` inside of `f` also does not work.

**Comment by materialsworld** [comment]
You've defined `runAndWait` twice. The `runAndWait` method is what tells the engine to start speaking. You should put the two pieces of text in one string, or if you need a pause, use the `time` module's `time.sleep()` function.

**Comment by LilithHafner** [comment]
> You should put the two pieces of text in one string, or if you need a pause, use the `time` module's `time.sleep()` function.

I would like to speak the first text before I know what the second text will be. How would you propose I accomplish this?

> this isn't because of the thread

For me, when running in the main thread, the function `f` produces the audio output "First sentence. Second Sentence." and when running in a separate thread it does not. Do you also observe this same behavior with the code I posted?

**Comment by LilithHafner** [comment]
Blocking the main thread is not an option in my application. I need to perform other tasks while audio is emitted.

**Comment by LilithHafner** [comment]
For context, the reason I would like to run tts from a thread other than main is to work around #4. Nevertheless, this is a bug in and of itself.
