### ISSUE TITLE
NameError: name 'objc' is not defined. Did you mean: 'object'?

### ISSUE THREAD

**Issue by onyekaokonji** [Akul-AI/rlvoice#5]
Came here from pyttx because of a comment I read but i still get same error messages.

I am using Python 3.11.6, if that matters.

Full error printout:

`Traceback (most recent call last):
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
          ~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/weakref.py", line 136, in __getitem__
    o = self.data[key]()
        ~~~~~~~~~^^^^^
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/onyekachukwuokonji/Desktop/try_all_sorts/auto_translator.py", line 7, in <module>
    rlv = rlvoice.init()
          ^^^^^^^^^^^^^^
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/driver.py", line 49, in __init__
    self._module = importlib.import_module(name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/drivers/nsss.py", line 13, in <module>
    class NSSpeechDriver(NSObject):
  File "/Users/onyekachukwuokonji/dexter/lib/python3.11/site-packages/rlvoice/drivers/nsss.py", line 14, in NSSpeechDriver
    @objc.python_method
     ^^^^
NameError: name 'objc' is not defined. Did you mean: 'object'?`

**Comment by llfstudyup1104** [comment]
hello @onyekaokonji , could you please give me any idea to solve this issue if you have resolved it. Thanks.

**Comment by onyekaokonji** [comment]
Hi @llfstudyup1104 I stumbled on this [package](https://pypi.org/project/py3-tts/) installed it and with that original pttsx3 package worked fine... didn't need to use rlvoice-1.
